- name: Add Multiple Vlans
  hosts: all
  gather_facts: false

  vars:
    vlans: {
        "100": {"description": "floor_1", "ip": "192.168.10.1"},
        "200": {"description": "floor_2", "ip": "192.168.20.1"},
        "300": {"description": "floor_3", "ip": "192.168.30.1"}  
      }

  tasks:
    - name: add vlans
      ios_config:
        lines:
          - vlan {{ item.key }}
      with_dict: "{{ vlans }}"
    - debug: var=print_output.stdout_lines

    - name: configure vlans
      ios_config:
        lines: 
          - description {{ item.value.name }}
          - ip address {{ item.value.ip }} 255.255.255.0
        parents: interface vlan {{ item.key }}
      with_dict: "{{ vlans }}"
    - debug: var=print_output.stdout_lines