---
- hosts: all
  gather_facts: no

  tasks:
    - name: set config on remote device (R1) #读取config文件，进行设定
      ios_config:
        src: "files/R1_config.txt"
        match: none   #幂等性OFF
        save_when: modified  #只有当配置被变更的适合保存，还有一种是写法是 save：yes，，即不论任何适合都保存
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}_backup_{{lookup('pipe','date +%Y%m%d')}}.log"
          dir_path: /home/kakazon/ansible_lab/backup
      when: inventory_hostname == 'R1'  #仅当对象OS是ios时才执行本操作
    
    - name: set config on remote device (R2) #读取config文件，进行设定
      ios_config:
        src: "files/R2_config.txt"
        match: none   #幂等性OFF
        save_when: modified  #只有当配置被变更的适合保存，还有一种是写法是 save：yes，，即不论任何适合都保存
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}_backup_{{lookup('pipe','date +%Y%m%d')}}.log"
          dir_path: /home/kakazon/ansible_lab/backup
      when: inventory_hostname == 'R2'  #仅当对象OS是ios时才执行本操作

    - name: set config on remote device (R3) #读取config文件，进行设定
      ios_config:
        src: "files/R3_config.txt"
        match: none   #幂等性OFF
        save_when: modified  #只有当配置被变更的适合保存，还有一种是写法是 save：yes，，即不论任何适合都保存
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}_backup_{{lookup('pipe','date +%Y%m%d')}}.log"
          dir_path: /home/kakazon/ansible_lab/backup
      when: inventory_hostname == 'R3'  #仅当对象OS是ios时才执行本操作