---
- name: run multiple commands on remote devices
  hosts: all
  gather_facts: false

  tasks:
        - name: show run backup
          ios_command:
             commands:
                      - show run

          register: print_output

        - debug: var=print_output.stdout_lines

        - name: save putput to a file
          copy: 
            content: "{{ print_output.stdout[0] }}" 
            dest: "/home/kakazon/ansible_lab/ansible_output/{{ inventory_hostname }}.txt"
